package com.dibe.carecoord.folders.viewmodel.util

enum class PatientField {
    NAME,
    AGE,
    SEX,
    OCCUPATION,
    MARITAL_STATUS,
    ADDRESS,
    TRIBE,
    HEIGHT,
    WEIGHT,
    BMI,
    PULSE,
    OXYGEN_SATURATION,
    SYS,
    DYS,
    LMP,
    EDD,
    GRAVIDITY,
    PARITY,
    KATAMENIA,
    COMPLAIN,
    HPC,
    GYNAE_HISTORY,
    MEDICAL_HISTORY,
    SOCIAL_HISTORY,
    DRUG_HISTORY,
    ROS,
    PHYSICAL_EXAMINATION,
    DIAGNOSIS,
    INVESTIGATION,
    TREATMENT,
    SUMMARY,
    UPDATE
}
